# Generated by Django 6.0.2 on 2026-05-05 19:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('per_user_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('first_time_user_only', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='coupons', to='catalog.category')),
                ('products', models.ManyToManyField(blank=True, related_name='coupons', to='catalog.product')),
            ],
        ),
    ]
